<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>OptiKey.ET5.Plugin.Synthetic</AssemblyName>
    <RootNamespace>OptiKey.ET5.Plugin.Synthetic</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <OutputPath>bin\$(Platform)\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\$(Platform)\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptiKey.ET5.Plugin\OptiKey.ET5.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="JuliusSweetland.OptiKey.Contracts">
      <HintPath>..\..\lib\contracts\JuliusSweetland.OptiKey.Contracts.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="4.4.1" />
  </ItemGroup>

</Project>
